# Build master branch and versions tags (on top of PRs).
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/


# Use latest available ubuntu (18.04).
os: linux
dist: bionic


# Configure the build jobs.
language: rust

# Cargo cache grows really fast for a few reason.
# Using the default configuration quickly leads to cache management times 
# to exceed un-cached build times and makes things worse.
# We use some tricks to cache some of the stuff but not everything in CI.
#
# See https://github.com/rust-lang/cargo/issues/5885
before_cache:
  - ci/travis/prep-cargo-cache.sh
cache:
  directories:
    - $HOME/.cargo
    - target/

rust:
  - stable   # Target rust version.
  - 1.43.0   # Earliest supported rust version.
  - nightly  # "The Rust team appreciates" according to Travis.

env:
  global:
    # Avoid re-compiling commmon crates by sharing the target directory.
    - CARGO_TARGET_DIR=target 
  jobs:
    - TASK=build
    - TASK=audit

install: ci/travis.sh install "${TASK}"
script:
  - ci/travis/cargo-clean-on-new-rustc.sh
  - ci/travis.sh script "${TASK}"

jobs:
  allow_failures:
    - rust: nightly
    - env: TASK=audit
  fast_finish: true
