# Build master branch and versions tags (on top of PRs).
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/


# Use latest available ubuntu (18.04).
os: linux
dist: bionic


# Configure the build jobs.
language: rust

# Cargo cache grows really fast for a few reasons and
# cache management times end up exceeding un-cached build times.
#
# A couple of attempts were made to optimise caching
# and the complexity of scripts was not worth it.
rust:
  - stable   # Target rust version.
  - 1.44.0   # Earliest supported rust version.
  - nightly  # "The Rust team appreciates" according to Travis.

env:
  global:
    # Avoid re-compiling commmon crates by sharing the target directory.
    - CARGO_TARGET_DIR=target 
  jobs:
    - TASK=build
    - TASK=audit

install: ci/travis.sh install "${TASK}"
script: ci/travis.sh script "${TASK}"

jobs:
  allow_failures:
    - rust: nightly
    - env: TASK=audit
  fast_finish: true
