[workspace]
members = [
    # Agent crates
    "base",
    "mongodb",
    "zookeeper",

    # Common crates
    "common/agent/models",
    "common/logging",
    "common/util/iron",
    "common/util/tracing"
]
