[workspace]
members = [
    # Agent crates
    "base",
    "mongodb",
    "zookeeper",

    # Official crates with complex dependencies are not in the workspace by default.
    #"kafka",

    # Common crates
    "common/agent/models",
    "common/logging",
    "common/util/iron",
    "common/util/tracing"
]
