[package]
name = "replicante_agent"
version = "0.2.0" # remember to update html_root_url
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
build = "build.rs"

description = "Replicante agent framework"
documentation = "https://docs.rs/replicante_agent"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/agents"
keywords = ["automation", "datastore", "operations"]
license = "MIT"


[lib]
name = "replicante_agent"
path = "src/lib.rs"


[badges]
maintenance = { status = "actively-developed" }


[dependencies]
error-chain = "^0.12.0"
iron = "^0.6.0"
iron-json-response = "^0.6.0"
lazy_static = "^1.0.1"
prometheus = { version = "^0.5.0", features = ["process"] }
router = "^0.6.0"
serde = "^1.0.25"
serde_derive = "^1.0.25"
serde_json = "^1.0.8"
serde_yaml = "^0.8.0"
slog = "^2.2.3"

opentracingrust = "^0.3.1"
opentracingrust_zipkin = "^0.1.2"

replicante_agent_models = { path = "../common/agent/models", version = "0.2.0" }
replicante_logging = { path = "../common/logging", version = "0.1.1" }
replicante_util_iron = { path = "../common/util/iron", version = "0.1.2" }
replicante_util_tracing = { path = "../common/util/tracing", version = "0.1.1" }


[build-dependencies]
git2 = "^0.8.0"


[dev-dependencies]
iron-test = "^0.6.0"


[features]
journald = ["replicante_logging/journald"]
